-- 数据库和表
CREATE datebase datebaseName;
DROP datebase datebaseName;
CREATE TABLE IF NOT EXISTS TABLE_NAME;
CREATE TABLE TABLE_NAME LIKE TABLE_NAME1;
CREATE TABLE TABLE_NAME AS SELECT COLUMN FROM TABLE_NAME1;
DROP TABLE IF EXISTS TABLE_NAME;
-- 列
ALTER TABLE TABLE_NAME ADD COLUMN COLUMN_NAME TYPE;
ALTER TABLE TABLE_NAME MODIFY COLUMN COLUMN_NAME TYPE;
ALTER TABLE TABLE_NAME DROP COLUMN COLUMN_NAME;
-- 设置主键
ALTER TABLE TABLE_NAME ADD PRIMARY KEY(COL);
ALTER TABLE TABLE_NAME DROP PRIMARY KEY(COL);
--索引
CREATE INDEX indexName ON TABLE_NAME(COL1,COL2);
DROP INDEX indexName;
-- 行
-- 插入
INSERT INTO TABLE_NAME(field1,field2) VALUES (value1,value2);
-- 修改
UPDATE TABLE_NAME SET field1 = value1,field2 = value2 WHERE id = 1;
-- 删除
DELETE FROM TABLE_NAME WHERE id = 1;
-- 查询
SELECT FROM TABLE_NAME WHERE id = 1;
-- 模糊查询
SELECT FROM TABLE_NAME WHERE id LIKE CONCAT('%','${abs}','%');
-- 降序 升序排列
SELECT FROM TABLE_NAME WHERE id LIKE CONCAT('%','${abs}','%') ORDER BY id DESC(ASC);
-- 查行数
SELECT COUNT(*) AS totalcount FROM TABLE_NAME WHERE id LIKE CONCAT('%','${abs}','%');
-- 求列和、平均、最大、最小
SELECT SUM(col) AS sumvalue FROM  TABLE_NAME
SELECT AVG(col) AS sumvalue FROM  TABLE_NAME
SELECT MAX(col) AS sumvalue FROM  TABLE_NAME
SELECT min(col) AS sumvalue FROM  TABLE_NAME
-- 同表联合查询
-- 两个结果集的并集 属于A或属于B
-- 不去重
SELECT FROM TABLE_NAME WHERE id = 1 UNION ALL SELECT FROM TABLE_NAME WHERE id = 2;
-- 去重
SELECT FROM TABLE_NAME WHERE id = 1 UNION SELECT FROM TABLE_NAME WHERE id = 2;
-- 两个结果集的交集 属于A且属于B
-- 不去重
SELECT FROM TABLE_NAME WHERE id = 1 INTERSECT ALL SELECT FROM TABLE_NAME WHERE id = 2;
-- 去重
SELECT FROM TABLE_NAME WHERE id = 1 INTERSECT SELECT FROM TABLE_NAME WHERE id = 2;
-- 两个结果集的差集 属于A但不属于B
-- 不去重
SELECT FROM TABLE_NAME WHERE id = 1 EXCEPT ALL SELECT FROM TABLE_NAME WHERE id = 2;
-- 去重
SELECT FROM TABLE_NAME WHERE id = 1 EXCEPT SELECT FROM TABLE_NAME WHERE id = 2;
-- 异表联合查询
-- 外连接
-- 左外链接
SELECT * FROM a LEFT JOIN b ON a.id = b.id WHERE a.id = 1;
-- 右外连接
SELECT * FROM a RIGHT JOIN b ON a.id = b.id WHERE b.id = 1;
-- 内连接
SELECT * FROM a INNER JOIN b ON a.id = b.id WHERE a.id = 1;
-- 内连接等价形式
SELECT * FROM a INNER JOIN b WHERE a.id = b.id AND a.id = 1;
-- 分组GROUP BY
SELECT id, sum(number), name FROM a WHERE number>100 GROUP BY id,name;
-- 与ORDER BY一起使用
SELECT id, sum(number), name FROM a WHERE number>100 GROUP BY id,name ORDER BY id DESC;
-- 子查询IN
SELECT id, sum(number), name FROM a WHERE number IN(SELECT number FROM b WHERE number>100) GROUP BY id,name ORDER BY id DESC;
-- 实例
-- 选择在每一组b值相同的数据中对应的a最大的记录的所有信息
SELECT * FROM TABLE_NAME t WHERE t.a = (SELECT max(a) FROM TABLE_NAME t1 WHERE t1.b = t.b);
-- 包括所有在TableA 中但不在 TableB和TableC 中的行并消除所有重复行而派生出一个结果表
SELECT * FROM TableA EXCEPT (SELECT * FROM TableB UNION SELECT * FROM TableC);
SELECT * FROM TableA EXCEPT (SELECT * FROM TableB) EXCEPT (SELECT * FROM TableC);
-- 删除重复记录
DELETE FROM TABLE_NAME WHERE id NOT IN (SELECT MAX(id) FROM TABLE_NAME GROUP BY col1,col2,...);
-- 选择第a到b条记录
SELECT * FROM TABLE_NAME WHERE id > 100 LIMIT a,b;
